version: "3.5"

services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        hostname: pihole.local
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "8181:80/tcp"
            - "8183:443/tcp"
        environment:
            TZ: 'Europe/Athens'
            WEBPASSWORD: 'password'
            DNS1: "172.20.0.3#5053"
            DNS2: "172.20.0.3#5053"
            FTLCONF_RATE_LIMIT: "2000/60"
        volumes:
            - './etc-pihole/:/etc/pihole/'
            - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
        dns:
            - 127.0.0.1
            - 1.1.1.1
        restart: unless-stopped
        labels:
            - "diun.enable=true"
            - "diun.include_tags=latest"
        networks:
            pihole:
                ipv4_address: 172.20.0.2

    cloudflare:
        image: ghcr.io/panosrob/cloudflared:latest
        container_name: cloudflare
        ports:
            - "39383:39383"
        environment:
            TUNNEL_DNS_ADDRESS: "0.0.0.0"
            TUNNEL_DNS_PORT: 5053
            TUNNEL_METRICS: "172.20.0.3:39383"
        restart: unless-stopped
        labels:
            - "diun.enable=true"
            - "diun.include_tags=latest"
        networks:
            pihole:
                ipv4_address: 172.20.0.3

networks:
    pihole:
        ipam:
            config:
                - subnet: 172.20.0.0/24
